spring.application.name=TopNews

##############################
#        DATABASE
##############################
spring.datasource.url=jdbc:postgresql://localhost:8081/top_news_db
spring.datasource.username=top_news_user
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

##############################
#        EMAIL
##############################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=sadriddindusanov@mail.ru
spring.mail.password=uhkSZHdOPhGgD7ZiNm23
spring.mail.protocol=smtps

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000

########################
#        Attach
########################
attache.folder=attaches
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
server.port=8080
server.url=http://localhost:${server.port}

########################
#        SMS
########################
company.email=top_news@gmail.com
company.password=12345

