###register
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Admin",
  "surname": "Adminov",
  "username": "+998987654321",
  "password": "12345"
}

###register
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Admin",
  "surname": "Adminov",
  "username": "+9981234567",
  "password": "54321"
}


###register
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Moderator",
  "surname": "Moderatorov",
  "username": "oqmol24@gmail.com",
  "password": "trewq"
}

###register
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "Publisher",
  "surname": "Publisherov",
  "username": "kumbay64@gmail.com",
  "password": "qwert"
}

###verify
POST localhost:8080/auth/verify
Content-Type: application/json

{
  "username": "+998987654321",
  "code": "537136"
}

###resend
POST localhost:8080/auth/resend-code?email=kumbay64@gmail.com

###login
GET localhost:8080/auth/login
Content-Type: application/json

{
  "username": "+998987654321",
  "password": "12345"
}

###login
GET localhost:8080/auth/login
Content-Type: application/json

{
  "username": "+998991234567",
  "password": "54321"
}