###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdXJuYW1lIjoiVHVyc3Vub3YiLCJyb2xlcyI6WyJST0xFX01PREVSQVRPUiJdLCJuYW1lIjoiTXVzbGltIiwiaWQiOjQ1LCJzdWIiOiJtdXNsaW1AZ21haWwuY29tIiwiaWF0IjoxNzgxNzEzNzY1LCJleHAiOjE3ODE3MTczNjV9.vQ611mzEM8LoePSdQB2HGtmTWQGVOsIPESFwghJgXMjZhXo2uNl5q2ecUofFqHyA


{
  "name": "Ali",
  "surname": "Valiyev",
  "username": "ali@gmail.com",
  "password": "ali123",
  "status": "ACTIVE",
  "roleList": ["ROLE_PUBLISHER"]
}

###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdXJuYW1lIjoiVHVyc3Vub3YiLCJyb2xlcyI6WyJST0xFX01PREVSQVRPUiJdLCJuYW1lIjoiTXVzbGltIiwiaWQiOjQ1LCJzdWIiOiJtdXNsaW1AZ21haWwuY29tIiwiaWF0IjoxNzgxNzEzNzY1LCJleHAiOjE3ODE3MTczNjV9.vQ611mzEM8LoePSdQB2HGtmTWQGVOsIPESFwghJgXMjZhXo2uNl5q2ecUofFqHyA

{
  "name": "Muslim",
  "surname": "Tursunov",
  "username": "muslim@gmail.com",
  "password": "muslim",
  "status": "ACTIVE",
  "roleList": ["ROLE_MODERATOR"]
}

###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Jasur",
  "surname": "Toshmatov",
  "username": "jasur@gmail.com",
  "password": "jasur123",
  "status": "ACTIVE",
  "roleList": ["ROLE_MODERATOR", "ROLE_PUBLISHER"]
}

###get profile list

GET localhost:8080/profile/list

###update admin
PUT http://localhost:8080/profile/admin-update/2
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Valiyev",
  "username": "ali_new@gmail.com",
  "status": "BLOCKED",
  "roleList": ["ROLE_MODERATOR"]
}

###update delail
PUT http://localhost:8080/profile/update-detail/3
Content-Type: application/json

{
  "name": "Sarvar",
  "surname": "Rahimov"
}

###update password
PUT http://localhost:8080/profile/update-password/1
Content-Type: application/json

{
  "currentPassword": "11111",
  "newPassword": "ali456"
}