###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Valiyev",
  "username": "ali@gmail.com",
  "password": "ali123",
  "status": "ACTIVE",
  "roleList": ["ROLE_MODERATOR"]
}

###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Sardor",
  "surname": "Rahimov",
  "username": "sardor@gmail.com",
  "password": "sardor123",
  "status": "ACTIVE",
  "roleList": ["ROLE_PUBLISHER"]
}

###create profile
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Jasur",
  "surname": "Toshmatov",
  "username": "jasur@gmail.com",
  "password": "jasur123",
  "status": "ACTIVE",
  "roleList": ["ROLE_MODERATOR", "ROLE_PUBLISHER"]
}

###get profile list
GET localhost:8080/profile/list

###update admin
PUT http://localhost:8080/profile/admin-update/2
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Valiyev",
  "username": "ali_new@gmail.com",
  "status": "BLOCKED",
  "roleList": ["MODERATOR"]
}

###update delail
PUT http://localhost:8080/profile/update-detail/3
Content-Type: application/json

{
  "name": "Sarvar",
  "surname": "Rahimov"
}

###update password
PUT http://localhost:8080/profile/update-password/1
Content-Type: application/json

{
  "currentPassword": "11111",
  "newPassword": "ali456"
}